schema_version: 1

context:
  name: azure-mgmt-media
  version: "10.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: d654dce92a85c3aeb251a7e0d0c8d8fa377d26ae4d38836ef69b85c9b4869113

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - msrest >=0.7.1
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - typing_extensions >=4.3.0

tests:
  - python:
      imports:
        - azure.mgmt.media
        - azure.mgmt.media.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Media Services Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
